DROP DATABASE IF EXISTS mh_db;
DROP ROLE IF EXISTS mh_db_user;
DROP TABLE IF EXISTS armor CASCADE;
DROP TABLE IF EXISTS armor_set CASCADE;
DROP TABLE IF EXISTS charm CASCADE;
DROP TABLE IF EXISTS decoration CASCADE;
DROP TABLE IF EXISTS hunter_art CASCADE;
DROP TABLE IF EXISTS monster_in_quest CASCADE;
DROP TABLE IF EXISTS quest CASCADE;
DROP TABLE IF EXISTS skill CASCADE;
DROP TABLE IF EXISTS skill_effect CASCADE;
DROP TABLE IF EXISTS submission CASCADE;
DROP TABLE IF EXISTS weapon CASCADE;


CREATE ROLE mh_db_user WITH LOGIN PASSWORD 'mh_password' CREATEDB;
CREATE DATABASE mh_db WITH
  OWNER mh_db_user;