DROP DATABASE IF EXISTS mh_db;
DROP ROLE IF EXISTS mh_db_user;
DROP SCHEMA public CASCADE;

CREATE SCHEMA public;
CREATE ROLE mh_db_user WITH LOGIN PASSWORD 'mh_password' CREATEDB;
CREATE DATABASE mh_db WITH
  OWNER mh_db_user;