INSERT INTO skill (name) VALUES('Ammo Saver');
INSERT INTO skill (name) VALUES('Anti-Theft');
INSERT INTO skill (name) VALUES('Artillery');
INSERT INTO skill (name) VALUES('Attack');
INSERT INTO skill (name) VALUES('Bherna');
INSERT INTO skill (name) VALUES('Bind Res');
INSERT INTO skill (name) VALUES('Biology');
INSERT INTO skill (name) VALUES('Blast C+');
INSERT INTO skill (name) VALUES('Bleeding');
INSERT INTO skill (name) VALUES('Blight Res');
INSERT INTO skill (name) VALUES('Blunt');
INSERT INTO skill (name) VALUES('Bomb Boost');
INSERT INTO skill (name) VALUES('Botany');
INSERT INTO skill (name) VALUES('Bubble');
INSERT INTO skill (name) VALUES('C.beard');
INSERT INTO skill (name) VALUES('C.Range C+');
INSERT INTO skill (name) VALUES('Capturer');
INSERT INTO skill (name) VALUES('Carnivore');
INSERT INTO skill (name) VALUES('Carving');
INSERT INTO skill (name) VALUES('Chain Crit');
INSERT INTO skill (name) VALUES('Chance');
INSERT INTO skill (name) VALUES('Charmer');
INSERT INTO skill (name) VALUES('Clust S+');
INSERT INTO skill (name) VALUES('Cold Res');
INSERT INTO skill (name) VALUES('ColdBlooded');
INSERT INTO skill (name) VALUES('Combo Plus');
INSERT INTO skill (name) VALUES('Combo Rate');
INSERT INTO skill (name) VALUES('Constitution');
INSERT INTO skill (name) VALUES('Crag S+');
INSERT INTO skill (name) VALUES('Crisis');
INSERT INTO skill (name) VALUES('Crit Draw');
INSERT INTO skill (name) VALUES('Crit Element');
INSERT INTO skill (name) VALUES('Crit Status');
INSERT INTO skill (name) VALUES('Critical Up');
INSERT INTO skill (name) VALUES('D. Fencing');
INSERT INTO skill (name) VALUES('Dead Eye');
INSERT INTO skill (name) VALUES('Deadeye');
INSERT INTO skill (name) VALUES('Def Lock');
INSERT INTO skill (name) VALUES('Defense');
INSERT INTO skill (name) VALUES('Destroyer');
INSERT INTO skill (name) VALUES('Dragon Atk');
INSERT INTO skill (name) VALUES('Dragon Res');
INSERT INTO skill (name) VALUES('Dreadking');
INSERT INTO skill (name) VALUES('Dreadqueen');
INSERT INTO skill (name) VALUES('Drilltusk');
INSERT INTO skill (name) VALUES('Eating');
INSERT INTO skill (name) VALUES('Elem C+');
INSERT INTO skill (name) VALUES('Elemental');
INSERT INTO skill (name) VALUES('Evade Dist');
INSERT INTO skill (name) VALUES('Evasion');
INSERT INTO skill (name) VALUES('Exhaust C+');
INSERT INTO skill (name) VALUES('Expert');
INSERT INTO skill (name) VALUES('FastCharge');
INSERT INTO skill (name) VALUES('Fate');
INSERT INTO skill (name) VALUES('Fencing');
INSERT INTO skill (name) VALUES('Fire Atk');
INSERT INTO skill (name) VALUES('Fire Res');
INSERT INTO skill (name) VALUES('Frenzy Res');
INSERT INTO skill (name) VALUES('Furor');
INSERT INTO skill (name) VALUES('Gathering');
INSERT INTO skill (name) VALUES('Gloves Off');
INSERT INTO skill (name) VALUES('Gluttony');
INSERT INTO skill (name) VALUES('Grimclaw');
INSERT INTO skill (name) VALUES('Grinder');
INSERT INTO skill (name) VALUES('Guard');
INSERT INTO skill (name) VALUES('Guard Up');
INSERT INTO skill (name) VALUES('Guts');
INSERT INTO skill (name) VALUES('Handicraft');
INSERT INTO skill (name) VALUES('Haphazard');
INSERT INTO skill (name) VALUES('Health');
INSERT INTO skill (name) VALUES('Hearing');
INSERT INTO skill (name) VALUES('Heat Res');
INSERT INTO skill (name) VALUES('Heavy Up');
INSERT INTO skill (name) VALUES('Hellblade');
INSERT INTO skill (name) VALUES('Hero Shield');
INSERT INTO skill (name) VALUES('Honey');
INSERT INTO skill (name) VALUES('HotBlooded');
INSERT INTO skill (name) VALUES('Hunger');
INSERT INTO skill (name) VALUES('Ice Atk');
INSERT INTO skill (name) VALUES('Ice Res');
INSERT INTO skill (name) VALUES('Insight');
INSERT INTO skill (name) VALUES('KO');
INSERT INTO skill (name) VALUES('Kokoto');
INSERT INTO skill (name) VALUES('Lasting Pwr');
INSERT INTO skill (name) VALUES('Light Eater');
INSERT INTO skill (name) VALUES('Loading');
INSERT INTO skill (name) VALUES('Maestro');
INSERT INTO skill (name) VALUES('Mounting');
INSERT INTO skill (name) VALUES('Mycology');
INSERT INTO skill (name) VALUES('Normal S+');
INSERT INTO skill (name) VALUES('Normal Up');
INSERT INTO skill (name) VALUES('Para C+');
INSERT INTO skill (name) VALUES('Paralysis');
INSERT INTO skill (name) VALUES('Pellet S+');
INSERT INTO skill (name) VALUES('Pellet Up');
INSERT INTO skill (name) VALUES('Perception');
INSERT INTO skill (name) VALUES('Pierce S+');
INSERT INTO skill (name) VALUES('Pierce Up');
INSERT INTO skill (name) VALUES('Poison');
INSERT INTO skill (name) VALUES('Poison C+');
INSERT INTO skill (name) VALUES('Pokke');
INSERT INTO skill (name) VALUES('Potential');
INSERT INTO skill (name) VALUES('Power C+');
INSERT INTO skill (name) VALUES('Precision');
INSERT INTO skill (name) VALUES('Protection');
INSERT INTO skill (name) VALUES('Psychic');
INSERT INTO skill (name) VALUES('Punish Draw');
INSERT INTO skill (name) VALUES('Ranger');
INSERT INTO skill (name) VALUES('Rapid Fire');
INSERT INTO skill (name) VALUES('Rec Level');
INSERT INTO skill (name) VALUES('Rec Speed');
INSERT INTO skill (name) VALUES('Recoil');
INSERT INTO skill (name) VALUES('Redhelm');
INSERT INTO skill (name) VALUES('Reload Spd');
INSERT INTO skill (name) VALUES('Sense');
INSERT INTO skill (name) VALUES('Sharpener');
INSERT INTO skill (name) VALUES('Sharpness');
INSERT INTO skill (name) VALUES('Sheathing');
INSERT INTO skill (name) VALUES('Silverwind');
INSERT INTO skill (name) VALUES('Sleep');
INSERT INTO skill (name) VALUES('Sleep C+');
INSERT INTO skill (name) VALUES('Snowbaron');
INSERT INTO skill (name) VALUES('Speed Setup');
INSERT INTO skill (name) VALUES('Spirit');
INSERT INTO skill (name) VALUES('Stam Drain');
INSERT INTO skill (name) VALUES('Stam Recov');
INSERT INTO skill (name) VALUES('Stamina');
INSERT INTO skill (name) VALUES('Status');
INSERT INTO skill (name) VALUES('Stonefist');
INSERT INTO skill (name) VALUES('Stun');
INSERT INTO skill (name) VALUES('Survivor');
INSERT INTO skill (name) VALUES('Team Player');
INSERT INTO skill (name) VALUES('TeamLeader');
INSERT INTO skill (name) VALUES('Tenderizer');
INSERT INTO skill (name) VALUES('Thunder Atk');
INSERT INTO skill (name) VALUES('Thunder Res');
INSERT INTO skill (name) VALUES('Thunderlord');
INSERT INTO skill (name) VALUES('Torso Up');
INSERT INTO skill (name) VALUES('Transporter');
INSERT INTO skill (name) VALUES('Tremor Res');
INSERT INTO skill (name) VALUES('Unscathed');
INSERT INTO skill (name) VALUES('Vault');
INSERT INTO skill (name) VALUES('Water Atk');
INSERT INTO skill (name) VALUES('Water Res');
INSERT INTO skill (name) VALUES('Whim');
INSERT INTO skill (name) VALUES('Wide-Range');
INSERT INTO skill (name) VALUES('Wind Res');
INSERT INTO skill (name) VALUES('Yukumo');
INSERT INTO skill (name) VALUES('---');